import React from "react";

import { download } from "../assets";
import { downloadImage } from "../utils";

const Card = ({ _id, name, prompt, photo }) => (
  <div className="rounded-xl group relative shadow-card hover:shadow-cardhover card">
    <img
      className="w-full h-auto object-cover rounded-xl"
      src={photo} // generated by AI
      alt={prompt}
    />
    <div className="group-hover:flex flex-col max-h-[94.5%] hidden absolute bottom-0 left-0 right-0 bg-[#10131f] m-2 p-4 rounded-md">
      {/* now, the same prompt will be appeared that we used to generate the image.. */}
      <p className="text-white text-md overflow-y-auto prompt">{prompt}</p>

      {/* wrapper div means it will wrap all other elements such as image, download button, name */}
      <div className="mt-5 flex justify-between items-center gap-2">
        <div className="flex items-center gap-2">
          {/* wrap the name */}
          <div className="w-7 h-7 rounded-full object-cover bg-purple-700 flex justify-center items-center text-white text-xs font-bold">
            {name[0]}
          </div>
          {/* render the entire name */}
          <p className="text-white text-sm">{name}</p>
        </div>
        {/* download button to download the 1024x1024 sized image.. */}
        <button
          type="button"
          onClick={() => downloadImage(_id, photo)}
          className="outline-none bg-transparent border-none"
        >
          <img
            src={download}
            alt="download"
            className="w-6 h-6 object-contain invert"
          />
        </button>
      </div>
    </div>
  </div>
);

export default Card;
